<?php

if( !defined( 'ERR_NONE' ) ) { define( 'ERR_NONE', '' ); }
if( !defined( 'ERR_INVALID_LOGIN_INFO' ) ) { define( 'ERR_INVALID_LOGIN_INFO', 'Your username and/or password is incorrect.' ); }
if( !defined( 'ERR_INVALID_LOGIN_CHARS' ) ) { define( 'ERR_INVALID_LOGIN_CHARS', 'Your username and/or password contain invalid characters.' ); }
if( !defined( 'ERR_SESSION_NOT_CREATED' ) ) { define( 'ERR_SESSION_NOT_CREATED', 'There was a problem creating your session. Please try again.' ); }

if( !defined( 'TIMEOUT' ) ) { define( 'TIMEOUT', 900 ); }

?>